fix error when parsing time
Sometimes timestamp does not have the millisecond part, hence its
failing like this
ValueError: time data '2017-04-28 12:04:53' does not match format '%Y-%m-%d %H:%M:%S.%f'